# Cobalt2 Color Palette
set -l background 193549
set -l black 000000
set -l blue 1478DB
set -l brightBlack 808080
set -l brightBlue 1478DB
set -l brightCyan 00ffff
set -l brightGreen 33ff00
set -l brightPurple cc00ff
set -l brightRed ff0000
set -l brightWhite ffffff
set -l brightYellow ffff00
set -l cyan 00c5c7
set -l foreground c7c7c7
set -l green 3AD900
set -l purple ff2c70
set -l red ff2600
set -l white c7c7c7
set -l yellow ffc600

set -l selection ffffff
set -l comment 0088ff
set -l orange ffb86c

# Syntax Highlighting Colors
set -g fish_color_normal $foreground
set -g fish_color_command $cyan
set -g fish_color_keyword ff9d00
set -g fish_color_quote $yellow
set -g fish_color_redirection $foreground
set -g fish_color_end $orange
set -g fish_color_error $red
set -g fish_color_param $purple
set -g fish_color_comment $comment
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator $green
set -g fish_color_escape ff9d00
set -g fish_color_autosuggestion $comment

# Completion Pager Colors
set -g fish_pager_color_progress $comment
set -g fish_pager_color_prefix $cyan
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $comment
